import assert from 'node:assert/strict';
const base = process.argv[2] || 'http://127.0.0.1:4321';
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const get = path => fetch(new URL(path, base));
const collection = await get('/recipes');
assert.equal(collection.status, 200, 'collection renders successfully');
assert.match(collection.headers.get('cache-control') || '', /no-store/, 'HTML does not add another data cache');
const html = await collection.text();
assert.match(html, /<h1[^>]*>The collection<\/h1>/);
assert.match(html, /action="\/recipes"/);
assert.doesNotMatch(html, /src="\/app.js"/);
assert.doesNotMatch(html, /application\/ld\+json/, 'collection does not claim to be a recipe');
assert.equal((await get('/')).status, 200);
const data = await (await get('/api/recipes')).json();
assert.ok(data.recipes.length, 'seed the local database before running SSR smoke checks');
for (const summary of data.recipes.slice(0, 2)) {
  const recipe = await (await get(`/api/recipes/${summary.id}`)).json();
  const response = await get(`/recipes/${summary.id}`);
  assert.equal(response.status, 200);
  const detail = await response.text();
  assert.ok(detail.includes(escape(recipe.title)), 'title is in server HTML');
  assert.ok(detail.includes(escape(recipe.ingredients[0])), 'ingredients are in server HTML');
  assert.ok(detail.includes(escape(recipe.instructions[0])), 'instructions are in server HTML');
  assert.ok(detail.includes(`content="${escape(recipe.title)} · Recipe Box"`), 'record-specific social title');
  assert.ok(detail.includes(`href="https://recipes.heuermann.xyz/recipes/${recipe.id}"`), 'canonical URL');
  const scripts = [...detail.matchAll(/<script\b[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)];
  assert.equal(scripts.length, 1, 'one JSON-LD recipe per page');
  const schema = JSON.parse(scripts[0][1]);
  assert.equal(schema['@type'], 'Recipe');
  assert.equal(schema.name, recipe.title);
  assert.equal(schema.url, `https://recipes.heuermann.xyz/recipes/${recipe.id}`);
  assert.deepEqual(schema.recipeIngredient, recipe.ingredients);
  assert.deepEqual(schema.recipeInstructions.map(step => step.text), recipe.instructions);
  for (const step of schema.recipeInstructions) {
    assert.ok(detail.includes(`id="${new URL(step.url).hash.slice(1)}"`), 'step URLs resolve to rendered instructions');
  }
}
const q = data.recipes[0].title.split(' ')[0];
const search = await get(`/recipes?q=${encodeURIComponent(q)}&sort=title`);
assert.equal(search.status, 200);
assert.match(await search.text(), /Search results/);
const tags = data.recipes[0].tags.slice(0, 2);
const params = new URLSearchParams();
tags.forEach(tag => params.append('tag', tag));
const filtered = await get(`/recipes?${params}`);
assert.equal(filtered.status, 200);
const filteredHtml = await filtered.text();
const filteredData = await (await get(`/api/recipes?${params}`)).json();
const renderedIds = [...filteredHtml.matchAll(/data-recipe-id="([^"]+)"/g)].map(match => match[1]);
assert.deepEqual(renderedIds, filteredData.recipes.map(recipe => recipe.id), 'SSR tag filtering matches API');
const missing = await get('/recipes/does-not-exist');
assert.equal(missing.status, 404);
assert.doesNotMatch(await missing.text(), /application\/ld\+json/, 'missing recipes emit no schema');
assert.equal((await get('/unknown-page')).status, 404);
assert.equal((await get(`/recipes?q=${'x'.repeat(501)}`)).status, 400);
assert.equal((await fetch(new URL('/api/recipes', base), { method: 'POST' })).status, 405);
assert.equal((await get('/api/not-a-route')).status, 404);
const mcp = await get('/mcp/invalid-secret');
assert.ok([401, 404, 406].includes(mcp.status), 'MCP routes remain separate from Astro');
console.log('SSR smoke checks passed: initial HTML, two recipe pages, metadata, Recipe JSON-LD, search, AND tags, 404s, validation, API and MCP routing.');
